/*
CREATE TABLE Drivers(
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	LicenceNo VARCHAR(20) NOT NULL DEFAULT '000ABC',
	FirstName VARCHAR(20),
	MiddleName VARCHAR(20),
	LastName VARCHAR(20),
	DateOfBirth Date, 
)*/
/*
CREATE TABLE Vehicles (
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	RegistrationPlate VARCHAR(10),
	IsDriving BIT NOT NULL DEFAULT 0,
	Latitude FLOAT NOT NULL DEFAULT 0,
	Longtitude FLOAT NOT NULL DEFAULT 0,
	Altitude FLOAT NOT NULL DEFAULT 0,
	DriverID INT FOREIGN KEY REFERENCES Drivers(ID),
)
*/